// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NYShipping.Data;

#nullable disable

namespace nyshipping_backend.Migrations
{
    [DbContext(typeof(NYShippingContext))]
    [Migration("20240820142148_AddWaterUsageAndWasteDisposal")]
    partial class AddWaterUsageAndWasteDisposal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NYShipping.Models.EnergyUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("ElectricityUsage")
                        .HasColumnType("double");

                    b.Property<double?>("GasUsage")
                        .HasColumnType("double");

                    b.Property<string>("Month")
                        .HasColumnType("longtext");

                    b.Property<double>("WaterUsage")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("EnergyUsages", (string)null);
                });

            modelBuilder.Entity("NYShipping.Models.WasteDisposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisposalMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<double>("TonsDisposed")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("WasteDisposals", (string)null);
                });

            modelBuilder.Entity("NYShipping.Models.WaterUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("GallonsUsed")
                        .HasColumnType("double");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WaterUsages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
